# Conclusion

Twitter is a valuable source of information regarding sentiment and perception of public health organizations, policies, and messages, and offers direct access into the discussions made by individuals affected by such policies. In order to better understand these discussions, this study performed text mining analysis using topic modeling to attain relationships between public health messages and user viewpoints. Topic modeling, performed through the use of *Latent Dirichlet Allocation*, provides a significant insight into the abstract discussion topics acquired from social media data. Tweets were assigned topics using the $\phi$ and $\theta$ parameters, which allowed for linking topics to conversations defined by each conversation's unique `conversation_id`. The results of this operation were conversations containing the Parent (CDC) Topic and all replies of varying Reply Topics. Multinomial Logistic Regression was then performed to model the causal relationship between a CDC Tweet and its Reply Tweets. The regression model shows how each CDC Topic affects the probability and distribution of the occurrences of each Reply Topic. Theese results can be used to more effectively understand public perception of the CDC and its public health messaging regarding mask mandates, health and sanitation, and vaccine efficacy, as well as controversial and divisive topics within social media discourse.