# Discussion

## Controversial Topics

The Topics generated by *Latent Dirichlet Allocation* show a pattern of discussion among users that indicates a strong mistrust in government programs regarding mask wearing, vaccine mandates, public health, and basic sanitation. The most "controversial" of these is the `Masks-Mask-Efficacy` topic, which generated the largest and most divisive conversations; much of this division is linked to changes in federal mask mandates, specifically around the January 20, 2021 executive order requiring mask wearing in federal buildings, and in March 8, 2021, when the CDC no longer required fully vaccinated Americans to social distance or wear masks indoors [@netburn_timeline_2021]. 

Understanding the controversy behind these topics is important in the field of science communication, as it allows for clearer messaging to individuals and communities of various educational and socioeconomic backgrounds, so that public health campaigns remain inclusive and available for all.

## Applications

Several useful potential applications for this research exist; first, by using topic modeling, a better understanding of public perception of government programs can be achieved by "boiling down" potentially millions of data points into a discrete set of topics. Second, the relationship between Reply Topics and Parent (CDC) Topics can be modeled through logistic regression to establish a direct connection between the semantic topic of a public health message and the topics of user discussion. This relationship is vital to understand as it allows for better tailoring of public health messaging and science communication in general. By using machine learning models such as *LDA*, organizations can predict the expected Topic of a given message, which then can be used in conjunction with a logistic regression model to predict the expected distribution of topics of replies.


# Conclusion

Twitter is a valuable source of information regarding sentiment and perception of public health organizations, policies, and messages, and offers direct access into the discussions made by individuals affected by such policies. In order to better understand these discussions, this study performed text mining analysis using topic modeling to attain relationships between public health messages and user viewpoints. Topic modeling, performed through the use of *Latent Dirichlet Allocation*, provides a significant insight into the abstract discussion topics acquired from social media data. Tweets were assigned topics using the $\phi$ and $\theta$ parameters, which allowed for linking topics to conversations defined by each conversation's unique `conversation_id`. The results of this operation were conversations containing the Parent (CDC) Topic and all replies of varying Reply Topics. Multinomial Logistic Regression was then performed to model the causal relationship between a CDC Tweet and its Reply Tweets. The regression model shows how each CDC Topic affects the probability and distribution of the occurrences of each Reply Topic. Theese results can be used to more effectively understand public perception of the CDC and its public health messaging regarding mask mandates, health and sanitation, and vaccine efficacy, as well as controversial and divisive topics within social media discourse.