# Introduction

<!-- ## Public Health Geography -->
<!-- Discuss how geography affects public perception of COVID and CDC. -->

Within the United States, recent trends have shown a large-scale decrease in public trust of not only government organizations (e.g., the CDC and FDA), but also science as a discipline [@munoz_who_2012; @choli_perceptions_2021; @huang_xenophobia_2020]. This skepticism and widespread mistrust are dangerous when placed into the context of ignorance regarding COVID-19 and public safety measures. Using social media (specifically, Twitter) as a source for public opinion, this paper aims to study the effects of messaging and public outreach measures by the CDC on public opinion and perception, with the intention of improving public health communication.

## Research Question

This study intends to answer the following research question; how can qualitative text mining methods be used to better understand public opinion, allowing for more effective public health messaging and science communication. In answering this question, this paper aims to develop the foundation of a method for predicting discussion topics on social media using *Latent Dirichlet Allocation (LDA)* -- an algorithm for topic modeling -- and  regression analysis, specifically multinomial logistic regression, for the purposes of increasing effectiveness of science communication programs. Much of the literature focuses on the societal effects and public perception of the COVID-19 pandemic *itself* [@garcia_topic_2021; @boon-itt_public_2020; @dubey_twitter_2020; @manguri_twitter_2020; @zulfikar_public_2020]. This study instead aims to measure user opinion from the perspective of public health geography by examining the relationship between the topics of Tweets by the CDC (defined as *CDC Topic* and *CDC Tweet*) and their effects on the topics of Tweets made in reply (*Reply Topic* and *Reply Tweet*). 