---
output: pdf_document
---

```{r setup, include = F}

library(dplyr)
library(readr)
library(stringr)
library(textmineR)
library(topicmodels)
library(SnowballC)
library(parallel)
library(quanteda)

# Read reply tweets from RDS file

reply_tweets <- read_rds("data/reply_tweets.Rds")


# Create some Twitter stopwords

twitter_stopwords <- c("amp", "rt", "co", "t", "cdcgov")


# Create a directory for models
model_dir <- "models/reply"
if (!dir.exists("models/reply")) {
    dir.create(file.path(getwd(), model_dir), recursive = T)
}


# Load the (sample) DTM from rds, if it exists
if (file.exists("data/reply_dtm_sample.Rds")) {
    reply_dtm_sample <- read_rds("data/reply_dtm_sample.Rds")
}
```

```{r sample-reply, eval = F}
reply_tweets_sample <- reply_tweets %>%
    slice_sample(prop = 0.2)
```

```{r cleantext}

rt_sample_corpus <- corpus(
    reply_tweets_sample$text,
    docnames = reply_tweets_sample$tweet_id
)
    

```


```{r reply-dtm-sample, eval = F}
source("createDTM.R")

if (!file.exists("data/reply_dtm_sample.Rds")) {
    reply_dtm_sample <- create_dtm(
        doc_vec = reply_tweets_sample$text,
        doc_names = reply_tweets_sample$tweet_id
    )
    write_rds(reply_dtm_sample, "data/reply_dtm_sample.Rds")
}
```

```{r calc-lda-k, eval = F}
# source("createLDA.R")

# Define a directory for LDA models...


k_list <- seq(2, 50, 1)



cores <- (detectCores() - 4)


cl <- makeCluster(cores)

clusterExport(cl, c("model_dir", "reply_dtm_sample"))


k_result <- parLapply(
    cl,
    X = k_list,
    fun = function(k) {
        filename <- file.path(model_dir, paste0(as.character(k), ".rda"))
        if (!file.exists(filename)) {
            lda <- textmineR::FitLdaModel(
                dtm = reply_dtm_sample,
                k = k,
                iterations = 200,
                burnin = -1,
                alpha = 0.1,
                beta = 0.05,
                calc_coherence = TRUE,
            )
            print(k)
            lda$k <- k
            write_rds(lda, file = filename)
            return(lda)
        } else {
            lda <- read_rds(lda)
            return(lda)
        }
    }
)

stopCluster(cl)
```

```{r CTM-init, eval = F}
# If we choose to run a CTM, put it here


sample_ctm <- topicmodels::CTM(
    x = reply_dtm_sample,
    k = 6
)
```