# Literature Review

While much research regarding text mining of Twitter data has focused specifically on the COVID-19 pandemic, few works have focused on examining the public perception of government entities within the social media discourse [@dubey_twitter_2020; @boon-itt_public_2020; @manguri_twitter_2020; @garcia_topic_2021]. By focusing instead on governmental organizations, it is possible to reach an understanding of why public health messaging has not achieved its intended goals within the U.S., such as with vaccine hesitancy, COVID-19 denial, and a shifting of the discourse towards "personal freedom". This study aims to provide both a qualitative and quantitative analysis of public perception, using the literature below as a foundation.

## Sentiment Analysis

Much research regarding public opinion on the COVID-19 pandemic uses *sentiment analysis*, a dictionary-based approach to quantifying user sentiment (i.e. emotional valence); while this approach is useful for exploratory analysis of user sentiment, shortcomings exist when applying this model to "short-text" formats such as social media microblogging, comments, and Twitter posts [@boon-itt_public_2020; @clavel_sentiment_2015; @dubey_twitter_2020; @garcia_topic_2021; @liu_sentiment_2012; @manguri_twitter_2020; @pak_twitter_2010]. Due to these shortcomings (i.e. because many Tweets in this corpus contain fewer than 10 words), sentiment analysis was not performed within this study, with the focus instead placed on abstract connections between topics generated by topic modeling described below in Section \@ref(latent-dirichlet-allocation).

Because sentiment analysis obtains scores of emotional valence by referencing a *sentiment dictionary*, context is often lacking in such analyses; phrases such as "good" and "not bad" are semantically similar when understood through natural language, but would receive possible scores of $+1$ and $-2$, respectively. Methodology exists for alleviating such issues, including @pak_twitter_2010, the results of sentiment analysis are not applicable or necessary for this study.

## Topic Modeling

Extensive literature exists for topic modeling of Twitter data -- most recent research studies public perception of the COVID-19 pandemic and its societal effects [@negara_topic_2019; @hong_empirical_2010; @garcia_topic_2021; @debortoli_text_2016; @boon-itt_public_2020; @bao_joint_2009; @alghamdi_survey_2015]. While topic modeling is a powerful text mining tool, some limitations exist when used on *short-text* data; many metrics used to quantify the effectiveness of *LDA* models, such as *coherence score*, do not apply as readily to *short-text* formats. For this study, much of the literature involved foundational theory and methodologies for implementing *LDA* within text mining (e.g., with the `textmineR` R package), as well as methods for data preprocessing when working with *short-text* Twitter data [@jones_textminer_2019; @rashid_fuzzy_2019; @debortoli_text_2016; @alghamdi_survey_2015]. Many studies performed topic modeling on Tweets containing keywords related to the COVID-19 pandemic, such as *coronavirus*, *covid*, *pandemic*, etc. [e.g., @garcia_topic_2021; @boon-itt_public_2020].
