---
# title: "Topic Modeling of Twitter Data regarding the CDC and the COVID-19 Pandemic"
title: "Public Perception of the CDC and the COVID-19 Pandemic through Topic Modeling and Qualitative Analysis"
authors:
  - name: Harrison Brown
    address:  Department of Geography and Planning, Appalachian State University
    email: brownhr@appstate.edu
date: "`r Sys.Date()`"

abstract: |
  Social media is a powerful source of data regarding individual perception of public health policy and related phenomena such as the COVID-19 pandemic. This study performs topic modeling -- a statistical method capable of determining abstract topics within collections of documents -- on approximately 300,000 Tweets from January 1, 2019, to September 21, 2021, to better understand user sentiment of potentially conversational topics within the discourse. Topic modeling is performed on Tweets by the CDC's official Twitter account *"\@CDCgov"* (*CDC Tweets*), as well as on Tweets that reply to, quote, or mention the CDC's Twitter handle (*Reply Tweets*). Topic modeling is done through use of the *Latent Dirichlet Allocation (LDA)* algorithm, with 11 distinct topics. The results of multinomial logistic regression show the relationship between topics of CDC Tweets and topics of Reply Tweets, leading to a quantification of the public health messages which are deemed divisive or controversial. The regression analysis indicates that the most "controversial" Tweets authored by the CDC were those relating to mask wearing and mask mandates, with significantly higher occurrences of replies regarding "Big Pharma", government skepticism, and vaccine efficacy skepticism. The results of this study indicate a widespread mistrust in governmental organizations, public health policies, and science communication in general; however, the methodology used can be applied to public health messaging, allowing organizations to better communicate with the public.

header-includes:
  \usepackage{graphicx}


bibliography: topicmodeling.bib
# csl: aag.csl
documentclass: IEEEtran
output: bookdown::pdf_document2
# output: rticles::ieee_article

---




<!-- ```{=html}
<style>
body{
  text-align: justify
}
</style>
``` -->

```{r setup, include=FALSE}
# source("~/R Projects/5800TwitteR/.Rprofile")

library(dplyr)
library(tidyverse)
library(stargazer)
library(xtable)
library(nnet)
library(kableExtra)
library(magick)

knitr::opts_chunk$set(echo = TRUE)
conversation_wide <- read_rds("conversation_topics_wide.RDS")
conversation_long <- readRDS("conversation_long_2.RDS")
LDA_Summary <- read_csv("LDA_Summary.csv")
mlr <- readRDS("mlr.RDS")

# mlr <- read_rds("mlr.RDS")
conv_nonzero <- conversation_long %>%
  filter(value > 0)
```



```{r child = "_introduction.Rmd"}

```

```{r child="_litreview.Rmd"}

```

```{r child = "_datacollection.Rmd"}

```

```{r child = "_methodology.Rmd"}

```

```{r child = "_results.Rmd"}

```

```{r child = "_discussion.Rmd"}

```

```{r child = "_conclusion.Rmd"}

```

# References {-}



<div id="refs">

<!-- \setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
\setlength{\parskip}{8pt}
\noindent  -->

</div>

\newpage

```{r child = "_appendix.Rmd"}

```



